name: Tasmota CI

on:
  workflow_dispatch:

jobs:
  base-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install PlatformIO
        run: |
          pip install -U platformio
          cp ./platformio_override_sample.ini ./platformio_override.ini
      - name: Run PlatformIO
        run: platformio run -e tasmota32c3
      - uses: actions/upload-artifact@v4
        with:
          name: tasmota32c3-custom
          path: ./build_output/firmware/tasmota32c3.bin
