name: Tasmota-Nous-A8T-Build
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup-Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Prepare PlatformIO
        run: |
          pip install platformio
          cp ./platformio_override_sample.ini ./platformio_override.ini
          sed -i 's/;default_envs = tasmota32/default_envs = tasmota32-DE/g' ./platformio_override.ini
          
          # Variable global für alle nachfolgenden Schritte sichern
          echo "PLATFORMIO_BUILD_FLAGS=-DUSE_CONFIG_OVERRIDE" >> $GITHUB_ENV

      - name: Run Build
        run: |
          pio run -e tasmota32-DE

      - uses: actions/upload-artifact@v4
        with:
          name: Tasmota-Nous-A8T
          path: ./.pio/build/tasmota32-DE/firmware.bin
